from typing import Dict, List, Optional

from pydantic import Field

from core.llm.output_schemas.base import LLMOutputBase


class OutlineSectionOutput(LLMOutputBase):
    """A single section in the generated outline."""

    title: str = Field(description="Section heading title")
    description: str = Field(
        description="1-2 sentence description of what this section should cover"
    )
    content_format: str = Field(
        description="One of: prose, bullets, table, mixed"
    )
    key_points: List[str] = Field(
        description="3-5 key points this section should cover"
    )


class DocumentOutlineOutput(LLMOutputBase):
    """Complete document outline generated by LLM."""

    document_title: str = Field(description="Title of the document")
    document_subtitle: Optional[str] = Field(
        default=None, description="Optional subtitle"
    )
    sections: List[OutlineSectionOutput] = Field(
        description="Ordered list of document sections"
    )


class SectionContentOutput(LLMOutputBase):
    """Generated content for a single section."""

    heading: str = Field(description="Section heading, may be refined from outline")
    content: str = Field(description="Main section content as formatted text")
    bullet_points: Optional[List[str]] = Field(
        default=None,
        description="Bullet points if content_format is bullets or mixed",
    )
    table_data: Optional[Dict] = Field(
        default=None,
        description="Table data as {headers: [str], rows: [[str]]} if content_format is table",
    )
    speaker_notes: Optional[str] = Field(
        default=None, description="Speaker notes for presentation slides"
    )
    key_takeaway: Optional[str] = Field(
        default=None, description="One-sentence key takeaway from this section"
    )


class SectionIterationOutput(LLMOutputBase):
    """Regenerated section content based on user feedback."""

    heading: str = Field(description="Section heading")
    content: str = Field(description="Revised section content")
    bullet_points: Optional[List[str]] = Field(default=None)
    table_data: Optional[Dict] = Field(default=None)
    speaker_notes: Optional[str] = Field(default=None)
    key_takeaway: Optional[str] = Field(default=None)
    changes_made: str = Field(
        description="Brief description of what was changed based on feedback"
    )


class DocumentReviewOutput(LLMOutputBase):
    """Quality review of the generated document."""

    overall_score: int = Field(description="Quality score 1-10")
    coherence_score: int = Field(
        description="Section flow and transitions score 1-10"
    )
    completeness_score: int = Field(
        description="Coverage of outline points score 1-10"
    )
    consistency_score: int = Field(
        description="Terminology and tone consistency score 1-10"
    )
    issues: List[Dict] = Field(
        default_factory=list,
        description="List of {section_title, issue_type, description, suggestion}",
    )
    approved: bool = Field(
        description="Whether the document passes quality review"
    )
